import logging
import os
from typing import List, Dict, Any
from src.core.agent import BaseAgent
from src.schema.venture_state import VentureState, OpportunityNode, StrategicOption

logger = logging.getLogger(__name__)

class VentureMemoAgent(BaseAgent):
    """
    The Synthesizer. Transforms the complex VentureState into a 
    brutally honest, high-signal Markdown Venture Memo.
    """
    def __init__(self, name: str = "VentureMemoAgent", kill_threshold: float = 7.0):
        super().__init__(name)
        self.kill_threshold = kill_threshold

    async def process(self, state: VentureState) -> VentureState:
        print(f"[{self.name}] Generating Venture Memos for {len(state.nodes)} opportunities...")
        
        memos = []
        for node_id, node in state.nodes.items():
            memo = self._generate_memo(node)
            memos.append(memo)
            
        # Store memos in state metadata for later retrieval/saving
        state.metadata["venture_memos"] = memos
        
        # Save to file if needed (optional)
        self._save_memos_to_disk(state.domain, memos)
        
        return state

    def _generate_memo(self, node: OpportunityNode) -> str:
        """
        Creates the Markdown memo and includes the Deep Research Master Prompt.
        """
        best_strategy = min(node.strategies, key=lambda x: x.kill_score) if node.strategies else None
        
        # ... (Verdict logic remains same) ...
        status = "✅ GO"
        if best_strategy and best_strategy.kill_score > self.kill_threshold: status = "❌ DOA"
        
        deep_research_prompt = self._build_deep_research_prompt(node, best_strategy)
        node.metadata["deep_research_prompt"] = deep_research_prompt

        memo = f"""# VENTURE MEMO: {node.title.upper()}
**Status:** {status} | **Venture Score:** {node.opportunity_score:.1f}/20

---

### 1. DER SCHMERZ & DIE LÜCKE
*   **The Gap:** {node.gap_description}

### 2. DIE WAFFE: {best_strategy.title if best_strategy else 'N/A'}
*   **Rationale:** {best_strategy.rationale if best_strategy else 'N/A'}

### 3. DER FRIEDHOF & DER SARGNAGEL
*   **Historical Pivot:** {node.strategic_insight}
*   **Kill Score:** {best_strategy.kill_score if best_strategy else '0.0'}/10
*   **Main Risk:** {best_strategy.skeptic_verdict if best_strategy else 'N/A'}

---

## 🚀 ULTIMATE DEEP RESEARCH PROMPT
*Kopiere diesen Prompt in Gemini Deep Research oder Perplexity für die finale Validierung:*

```text
{deep_research_prompt}
```

---
*Generated by Venture Analyst Machine v1.0*
"""
        return memo

    def _build_deep_research_prompt(self, node: OpportunityNode, strategy: StrategicOption) -> str:
        """
        Synthesizes all agent findings into a surgical research mission.
        """
        return f"""Act as a Tier-1 Venture Capital Analyst. I need a Deep Research Report on a specific market gap in '{node.title}'.

CONTEXT:
- Preliminary findings suggest a gap: {node.gap_description}
- Proposed Strategy: {strategy.title if strategy else 'N/A'} ({strategy.strategy_type if strategy else ''})
- Target User: {node.actor}

RESEARCH MISSION:
1. VALIDATE THE PAIN: Find evidence of '{node.core_task}' causing significant financial or operational loss for {node.actor}.
2. COMPETITOR ATTACK: Deep dive into {', '.join(node.competitors[:3])}. Specifically, look for user complaints regarding {', '.join(node.weakness_patterns[:2])}. 
3. HISTORICAL AUTOPSY: Investigate why {', '.join(node.historical_attempts[:2])} failed. Verify if our hypothesis ('{node.strategic_insight}') correctly bypasses the blocker '{', '.join(node.structural_constraints[:1])}'.
4. SKEPTIC CHALLENGE: Critically assess the risk of '{strategy.risks[0].critique if strategy and strategy.risks else 'Market Saturation'}'. Is this a standalone company or just a feature for incumbents?
5. MARKET TIMING: Look for recent (last 6 months) changes in {', '.join([s.category for s in node.timing_signals[:2]])} that enable this now.

OUTPUT REQUIREMENTS:
- Minimum 2000 words.
- Cite specific sources, Reddit threads, and G2 reviews.
- Provide a clear 'Invest/Pass' recommendation based on the MOAT potential.
"""

    def _format_risks(self, strategy: StrategicOption) -> str:
        if not strategy or not strategy.risks:
            return "* No immediate fatal risks identified."
        
        risk_lines = []
        for r in strategy.risks:
            risk_lines.append(f"* **{r.vector} ({r.severity}):** {r.critique}")
        return "\n".join(risk_lines)

    def _save_memos_to_disk(self, domain: str, memos: List[str]):
        os.makedirs("reports", exist_ok=True)
        safe_domain = domain.replace(" ", "_").lower()
        filepath = f"reports/venture_memos_{safe_domain}.md"
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n\n---\n\n".join(memos))
        print(f"  [MEMO SAVED] {filepath}")
