import pandas as pd
import os
from datetime import datetime

# Paths
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
CSV_PATH = os.path.join(BASE_DIR, "workspace", "swiss_cantons_summary.csv")
REPORT_PATH = os.path.join(BASE_DIR, "workspace", "executive_summary_cantons.md")

def generate_report():
    print(f"📊 [Report-Generator] Starting Analysis... {datetime.now().isoformat()}")
    
    if not os.path.exists(CSV_PATH):
        print(f"⚠️  CSV not found at {CSV_PATH}. Run aggregation first.")
        return

    try:
        df = pd.read_csv(CSV_PATH)
        
        # 1. Economic Comparison
        # We group by canton and extract the 'Wirtschaft' column
        comparison = []
        for index, row in df.iterrows():
            comparison.append(f"### {row['Canton_ID'].replace('canton_', '').capitalize()}\n"
                              f"- **Hauptort**: {row['Hauptort']}\n"
                              f"- **Stärken**: {row['Wirtschaft']}\n")

        # 2. Statistics
        total_pop = df['Einwohner'].sum() if 'Einwohner' in df.columns else 0
        avg_duration = df['Duration'].mean() if 'Duration' in df.columns else 0

        # 3. Build Markdown
        md_content = f"""# 🛡️ Iron Fortress: Swiss Canton Research Summary
**Generated at**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Total Cantons**: {len(df)}
**Estimated Total Population**: {total_pop:,}
**Avg research time per unit**: {avg_duration:.2f}s

---

## 📈 Economic Landscape (Competitive Analysis)
{"".join(comparison)}

---
*Autonomous Report generated by Antigravity AI.*
"""
        with open(REPORT_PATH, "w", encoding="utf-8") as f:
            f.write(md_content)
        
        print(f"✅ [Report-Generator] Executive Summary saved to {REPORT_PATH}")

    except Exception as e:
        print(f"❌ [Report-Generator] Error generating report: {e}")

if __name__ == "__main__":
    generate_report()
